"""Make email unique plus validation

Revision ID: 75a372fa9def
Revises: 987ccc7d05e8
Create Date: 2025-09-06 14:51:42.356206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75a372fa9def"
down_revision: Union[str, Sequence[str], None] = "987ccc7d05e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "subscription", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subscription", type_="unique")
    # ### end Alembic commands ###
